### ISSUE TITLE
Stopping counts as a watched

### ISSUE THREAD

**Issue by tedrock** [ljunkie/plexWatch#104]
When you press stop in Plex, plexWatch counts that as watched in the database.

I'm not sure if this is intentional but it really messes up the charts and stats due to this. To me media should be considered watched when stopped and it's reached 90-100% (whatever percent Plex currently uses) complete.

plexWatch/Web Version: v1.5.4.2
plexWatch Version: v0.3.3-DEV

![example](https://cloud.githubusercontent.com/assets/1725926/8506618/7687c3fe-21eb-11e5-909f-7b3b5acf0859.PNG)

**Comment by ljunkie** [comment]
The intention is not to only show content that has been fully watched, it's to log what happens. It will log the start/stop regardless of percentage watched. There is however, an option to group watches within a few hours (~2 hours) of each other for the same item, so if you stopped and started the same item multiple times within ~2 hours, it will group those together and only show one line. Make sure you have selected to use the group options in the settings of PlexWatchWeb. 

You can change how many hours between watches should be grouped in the `config.pl` ```$watched_grouping_maxhr = 2;  ## advanced config -- do not group shows together if start/restart is > X hours```. The grouped table is rebuilt ~24 hours, so you may need to wait a bit for that setting to take effect.

**Comment by tedrock** [comment]
Wow, thank you for this very informative and quick response. I will go make those changes right away.
