### ISSUE TITLE
How do you completely remove PlexWatch from Linux server?

### ISSUE THREAD

**Issue by NedtheNerd** [ljunkie/plexWatch#105]
Whilst the installation instructions are pretty comprehensive, I cannot find any removal instructions.  

I have used PlexWatch for over a year, but no longer wish to continue using it.

Thanks.

**Comment by Arcanemagus** [comment]
It should be as simple as deleting the directory that contains it, and removing any crontab entries you entered.

If you are also looking to remove any packages you installed on your system to get plexWatch operational you would need to compare your system's installation instructions for the package names and use your system's package manager to remove those.

**Comment by ljunkie** [comment]
Thanks for answering @Arcanemagus. That's basically it. Really it's just killing the crontrab entries and optionally removing the plexWatch directory. It doesn't take much space, other than additional DB backups. The other parts installed are just perl modules, so it doesn't hurt to keep them installed. As @Arcanemagus mentioned, you can use the systems package manager to remove them (gui, apt-get, rpm, etc). It's not harmful to just leave those packages as is, removing could be more harmful as they are shared system packages.

**Comment by NedtheNerd** [comment]
Thanks for the responses.
