### ISSUE TITLE
What does watched_show_completed do?

### ISSUE THREAD

**Issue by tedrock** [ljunkie/plexWatch#106]
Could we get an example of exactly what watched_show_completed does? I know it says "always show completed show/movie as it's own line" but some sort of example showing the different would be appreciated.

I apologize for submitting this as a issue but the plex forums are still down and there's no contact info anywhere.

**Comment by ljunkie** [comment]
PlexWatch by default will group items started/stopped within ~2 hours of each other for the same item. If the user reaches 100%, and restart the item again within those two hours, it will show a line for the 100% completion, and another for the restart. If you disable `watched_show_completed`, then it will only show one line item for the scenario above, and won't sow 100% completion.

Once real world example. User has set to repeat the show, movie. If they watched the show back to back 5 times, then you'd see 5 watched items at 100% with `watched_show_completed` on, and only 1 watched item with `watched_show_completed` off.
