### ISSUE TITLE
stats.php line 242

### ISSUE THREAD

**Issue by trackermb** [ljunkie/plexWatch#108]
Hi there saw that the maxhourly plays chart was pulling DD MMM on the x Axis this can be fixed by copy line 214 and replacing line 242.  Finished line should look like 

return moment(x).format('<?php echo $settings->getTimeFormat(); ?>');

Cheers 
Mark

**Comment by ljunkie** [comment]
I think you want https://github.com/ecleese/plexWatchWeb :)
