### ISSUE TITLE
plexewebwatch 

### ISSUE THREAD

**Issue by marciobooi** [ljunkie/plexWatch#109]
can please someone write one installation totorial for mac for dummies, or create a batch install that make everything automatic? like a batch for windows or a script for mac that install everything in the right place and save the user (noob like me) all the hard work and the probability that will not work.
i see the images and i liked a lot but i cant make work
thanks for everyting

**Comment by Arcanemagus** [comment]
@marciobooi are you talking about https://github.com/ecleese/plexWatchWeb?

If so I would recommend looking into https://github.com/drzoidberg33/plexpy as it is better suited to the task (and removes the dependency on plexWatch as well).
