### ISSUE TITLE
SSL issue with 15.10

### ISSUE THREAD

**Issue by broyuken** [ljunkie/plexWatch#113]
I just updated to 15.10 and my plexwatch stopped working with prowl. When I try to run my cronjob manually, I get the following.

user@hostname:/opt/plexWatch$ /opt/plexWatch/./plexWatch.pl --recently_added=movie,tv
PROWL - Notification not posted: The%20Ellen%20DeGeneres%20Show%3A%20Seth%20Rogen%2C%20Justin%20Bieber%2C%20Leon%20Bridges%20s13e47%20%5BTV%2DG%5D%20%5B2015%5D%2041min%20%5B720p%206ch%5D%20%5B3%3A02PM%2012%20Nov%2015%5D SSL_verify_mode must be a number and not a string at /usr/share/perl5/IO/Socket/SSL.pm line 2130.

**Comment by broyuken** [comment]
Can we please get an update?

**Comment by Apocrathia** [comment]
I just submitted pull request 115 to fix this. Was having the same issue.
https://github.com/ljunkie/plexWatch/pull/115

**Comment by ljunkie** [comment]
Thanks for the PR @Apocrathia. I have pushed it to the dev branch for now, and plan to get it in master _soon_

**Comment by ljunkie** [comment]
it's in master now, thanks again @Apocrathia
