### ISSUE TITLE
Plex Media Server.log when plexWatch is on a different server than PMS

### ISSUE THREAD

**Issue by rayk32** [ljunkie/plexWatch#117]
How do you deal with these statement when plexWatch and PMS are running on different servers?

$server_log = '/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/Plex Media Server.log'; ## used to log IP address of user (alpha)
$log_client_ip = 1; ## requires $server_log to be available too. (requires File::ReadBackwards)

This is the error message I get:

warning: $server_log is specified in config.pl and opt/plexWatch/Logs/plex.log does not exist (required for logging of the clients IP address)

Everything else about plexWatch works except for this.

**Comment by Arcanemagus** [comment]
You need to provide some way for the plexWatch computer to access the logs directory if you want that functionality, generally this is handled with a network share of some sort.

**Comment by rayk32** [comment]
I think the correct path is /Users/admin/Library/Logs/Plex Media Server.log.

**Comment by rayk32** [comment]
Thanks for the response. I will follow your suggestion.

I think the correct path on a Mac running PMS is "/Users/admin/Library/Logs/Plex Media Server.log”.

**Comment by rayk32** [comment]
Creating a mount poing entry in fstab fixed the issue!
