### ISSUE TITLE
Install on windows

### ISSUE THREAD

**Issue by zzzbatmand** [ljunkie/plexWatch#126]
How do i install plexWatch on windows?

**Comment by Arcanemagus** [comment]
I would highly suggest looking into [PlexPy](https://github.com/drzoidberg33/plexpy), as this project is in a bugfix only state. Windows installation instructions for that can be found [here](https://github.com/drzoidberg33/plexpy/wiki/Installation#windows).

**Comment by zzzbatmand** [comment]
@Arcanemagus Thanks for the tip, it works great :)
