### ISSUE TITLE
Enhancement - Notify Albums/Tracks listened to in Music Libraries.

### ISSUE THREAD

**Issue by NedtheNerd** [ljunkie/plexWatch#59]
Title says it all.

Regards

**Comment by jordansaints** [comment]
Reviving this.  Has there been any thought given to this feature request?  I too would love to be able to see what music is being listened to in my library, in the same way that plexWatch currently lets us see which videos are being watched.  I'll fork the repo and play with it some time later this week and see what I can come up with, but maybe someone here has already given thought to this?  Thanks!!  :)

**Comment by UdinRex** [comment]
This would be great!

**Comment by mdemille** [comment]
+1

**Comment by painfulsedative** [comment]
+100!  I use Plex for all of my media and it would be amazing to keep track of what music has been listened to the most and by whom.  It would be nice to see what my kids are listening to as well.

**Comment by ljunkie** [comment]
Sorry all. I don't plan on adding music (or photos) to plexWatch. I'd suggest to look at plexPy for that.
