### ISSUE TITLE
Feature Request: Multiple Server Monitor

### ISSUE THREAD

**Issue by Keelan** [ljunkie/plexWatch#66]
I have two plex servers (Movies/TV Shows) but we can only enter one ip to monitor.

**Comment by elRadix** [comment]
+1 vote

**Comment by TheDogg** [comment]
+1 
I have 2 servers and would love to only have 1 plexwatch to configure/run

**Comment by elRadix** [comment]
I am currently running 2 instance of plexwatch to track my both servers, not the best option but it's something...

**Comment by shutchi2** [comment]
A very useful feature on PlexNotify that would be good here also.

**Comment by ljunkie** [comment]
Sorry all, but this is not going to be added to plexWatch. I'd suggest running different copies of plexWatch to support multiple servers.

To note, I'd think the web interface could be updated a bit easier to toggle between different servers (not a feature yet, but something maybe to add as a GHI there). I'd invision a drop down to selected which server you want to view, and the web interface just switches between plexWatch databases.
