### ISSUE TITLE
Feature request: notify users of new additions (email)

### ISSUE THREAD

**Issue by Deepcuts** [ljunkie/plexWatch#76]
Would love to see this feature.
I do not know if this is possible but would be much more useful to be able to notify your users of new additions instead of getting myself notified.
I have PlexWatchWeb to see what is going on on the server.

**Comment by Deepcuts** [comment]
Please consider the request fulfilled :)
https://github.com/bstascavage/plexReport does exactly what I need.

Thank you.

**Comment by ljunkie** [comment]
and better!
