### ISSUE TITLE
ReadMe - A Few Tiny Typos

### ISSUE THREAD

**Issue by war59312** [ljunkie/plexWatch#78]
Hi,

A few tiny ReadMe typos.

See: https://github.com/ljunkie/plexWatch/blob/master/README.md#these-should-be-part-of-the-bast-perl-install

Replace:

"These should be part of the bas**t** Perl install"

With:

"These should be part of the bas**e** Perl install"

"t" to "e"

Also see: https://github.com/ljunkie/plexWatch/blob/master/README.md#notification-format

What's up with the "g" right above that?

And the line break a little bit later within the quote field?

Thanks,

Will

**Comment by Arcanemagus** [comment]
@war59312 You should be able to click the edit button at the top of the Readme and submit a pull request that @ljunkie can then simply merge in the fixes automatically :wink: 

If you include a link to this Issue in the description of the Pull Request they will be automatically merged so when the pull request is completed this is marked as closed.

**Comment by war59312** [comment]
OK, done. Cool. My first. Think I got it right.

Easy. I love it. :)
