### ISSUE TITLE
Feature Request: Run command when watching/ending show

### ISSUE THREAD

**Issue by broyuken** [ljunkie/plexWatch#83]
I would like to be able to run a command whenever plexWatch notifies me that a show or movie is being watched, and when it is done. The main reason I want to do this is so I can pause my torrents/set alternative speeds on them while plex is streaming, and then go back to full speed when it is done. I looked through the documentation and didn't find anything that could do this  out of the box. I tried to redirect the output of plexWatch.pl to a file but there is no output to terminal.

**Comment by Arcanemagus** [comment]
Have you looked into the external section of the config? This does exactly what you are asking for already.

**Comment by broyuken** [comment]
wow, not sure how I completely overlooked that. Looks like this will do more or less what I want with some tweaking, just gotta figure out how to change the commands that get run.

**Comment by Arcanemagus** [comment]
Glad to hear that, if that's the case this issue should probably be closed :wink:

**Comment by broyuken** [comment]
It probably can, unless you can help me out with a problem I'm having setting this up. I'm new to perl scripting and this code is a little over my head so I'm not sure how to get it working. I created /usr/local/bin/start.pl with the contents

 system("transmission-remote -as");

when I run "perl /usr/local/bin/start.pl" manually it works just fine, but the script isn't working automatically with plexWatch. start.pl has rwx for my user, the same user that runs the plexwatch cron job. When I try to run the script command listed in config.pl, I get the following error

/usr/local/bin/start.pl: line 1: syntax error near unexpected token `"transmission-remote -as"'
/usr/local/bin/start.pl: line 1: `system("transmission-remote -as");'

What am I supposed to do to get this working? I'm lost if you could help me out.

**Comment by Arcanemagus** [comment]
Oh I don't have any rights to this repository, you should be able to close it via a button in the top right of this page though.
