### ISSUE TITLE
Exclude Library IDs Broken?

### ISSUE THREAD

**Issue by MikeFalcor** [ljunkie/plexWatch#90]
The very last part of the config file....sigh...

I am trying to exclude my section 6 (Anime), but no matter what I try it keeps including it.

Tried:
@exclude_library_ids = (6,);
@exclude_library_ids = (6);

And before you ask, no, it is NOT commented out... ;)

This WAS working just fine.  Then I removed a section and re-added the same section later with different media scanners.  Now I can't exclude it to save my life.

**Comment by ljunkie** [comment]
If you removed the library, then the ID will change. It's not very intuitive, but there is an easy way to see the current libraries and id. 

`/opt/plexWatch/plexWatch.pl --recently_added`

**Comment by MikeFalcor** [comment]
Yup!  I know that the ID changes.  The ID used to be 3, now it is 6.  Verified by plex media scanner and by Plex Management web UI.

**Comment by MikeFalcor** [comment]
Sorry, this isn't your problem.  It's plexWatch/Web.  Heading over there now! :)  Close me!
