### ISSUE TITLE
Historical watches?

### ISSUE THREAD

**Issue by olimortimer** [ljunkie/plexWatch#95]
Is there any way of 'importing' historical watches into plexWatch?  Ie, films etc that have been watched prior to installing plexWatch, using the Plex logs?

**Comment by ljunkie** [comment]
No. Plex logs in genreal are ephemeral, and the fact plexWatch does not use the logs, except for parsing the IP address of the user.

**Comment by olimortimer** [comment]
I don't get any IP addresses against users in plexWatch

**Comment by Arcanemagus** [comment]
@olimortimer Make sure you read through the requirements for IP address logging: https://github.com/ljunkie/plexWatch#required-only-if-client-ip-logging-is-enable
